### ISSUE TITLE
Start of the code review process 👋

### ISSUE THREAD

**Issue by minhnimble** [huuphuoc1396/android-nimble-surveys#18]
Hello Phuoc 👋 , thank you for your effort on the code submission. I am Mike, Engineering Lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by minhnimble** [comment]
Hi, Phuoc 👋

For your information, I just complete the 1st round of review now. Please go ahead and provide your feedback on all the proposed issues. If you have any further inquiry, please don't hesitate to communicate them here.

Have a great evening!

**Comment by huuphuoc1396** [comment]
Hi Mr. Mike,

Thank you for your effort in the reviews. I will check all issues and resolve them to improve the code submission.

Have a happy evening, too!

**Comment by minhnimble** [comment]
Good afternoon Quang ☀️

As of this point, this code challenge review session has concluded, and thus, no more submissions will be needed from your end. For the next step, you will hear from the Talent Acquisition team about the decision as soon as it is available. 🙏

Ultimately, it was a pleasure reviewing your code and getting to know you. Thanks for your time, and I wish you all the best! 🍀

**Comment by minhnimble** [comment]
Good afternoon Phuoc ☀️

As of this point, this code challenge review session has concluded, and thus, no more submissions will be needed from your end. For the next step, you will hear from the Talent Acquisition team about the decision as soon as it is available. 🙏

Ultimately, it was a pleasure reviewing your code and getting to know you. Thanks for your time, and I wish you all the best! 🍀

**Comment by huuphuoc1396** [comment]
Dear Mr. @minhnimble,

Thank you for your time in this review session. I have gained many things from you. 

Have a great weekend!
