### ISSUE TITLE
[Chore] Increase test coverage for the application

### ISSUE THREAD

**Issue by minhnimble** [huuphuoc1396/android-nimble-surveys#22]
## Issue

It was great to see you have implemented multiple unit test cases for multiple layers like the Usecase (domain layer), ViewModel (app layer), Repository + Response classes (data layer). Now, it is a bit odd that you didn't write any unit tests for the `HomeViewModel`, which is the most important logic file in the application.

https://github.com/huuphuoc1396/android-nimble-surveys/blob/2b94876ed1f9fa6995dd5e0f2af7807f0cb85781/app/src/test/java/co/nimblehq/surveys/features/home/HomeViewModelTest.kt#L11-L27

Also, there is no instrumented test found in the application. It would be great if a few instrumented tests to verify some basic flows in the application could be provided.

## Expect

- The test coverage for this project can be improved to reach above 80% for all the ViewModel classes used.
   ![Screenshot 2023-11-29 at 18 44 17](https://github.com/huuphuoc1396/android-nimble-surveys/assets/70877098/2f6850c8-d851-4aa0-9589-73d464155b48)

- Create some instrumented tests with Expresso for verifying a simple flow (e.g. open the Survey Lists screen from the Login screen) in the application.

**Comment by huuphuoc1396** [comment]
Hi @minhnimble, 

- Unit Test: I have implemented `HomeViewModelTest` to verify logic in the `HomeViewModel`.
- Instrumented Test: I have implemented `LoginScreenTest` to verify login inputs, login button enabled status, and click to login action.

Kindly help me check it, Thank you!
