### ISSUE TITLE
[Feature] Unit Test Enhancement 

### ISSUE THREAD

**Issue by huuphuoc1396** [huuphuoc1396/android-nimble-surveys#32]
- [x] Implement `EncryptedUserDatastoreImplTest`
- [x] Apply Kover to export coverage testing report
- [x] Migrate `JUnit4` to `JUnit5`

**Comment by dquang0706** [comment]
Migrate JUnit4 to JUnit5 was causing issue and need more time to research

**Comment by dquang0706** [comment]
Line Coverage:

Meaning: Line coverage measures the percentage of lines of code that have been executed during the testing process.
Calculation: It is calculated as the number of lines of code executed by tests divided by the total number of lines of code in the program.
Example: If you have a function with 10 lines of code, and your tests execute 8 of those lines, you would have 80% line coverage.
Branch Coverage:

Meaning: Branch coverage measures the percentage of decision points (branches) in your code that have been executed during testing.
Calculation: It is calculated as the number of decision points that have been taken (true or false) divided by the total number of decision points in the program.
Example: If you have an if statement in your code, it creates a decision point. If the condition is true in your tests, one branch is covered; if false, the other branch is covered. If you have 10 such decision points and your tests execute 8 of them, you would have 80% branch coverage.

**Comment by dquang0706** [comment]
**Coverage Report**

App Module:

<img width="1512" alt="image" src="https://github.com/huuphuoc1396/android-nimble-surveys/assets/42372848/d5afb96c-126e-45e5-8c70-73e99c206c3b">

Domain Module:

<img width="1512" alt="image" src="https://github.com/huuphuoc1396/android-nimble-surveys/assets/42372848/b30f4938-1870-4770-a631-a8f9a6bf967f">

Data Module:

<img width="1512" alt="image" src="https://github.com/huuphuoc1396/android-nimble-surveys/assets/42372848/9b28f021-4772-46fd-be12-d3d8cac1aedc">

**Comment by dquang0706** [comment]
Migrate Compose UI Test with JUnit5 can following this comment: https://github.com/mannodermaus/android-junit5/issues/234#issuecomment-1551463208
